[package]
name = "vsdb_trie_db"
version = "0.20.2"
edition = "2021"
keywords = ["mpt", "trie", "database", "blockchain"]
license = "MIT"
authors = ["hui.fan@mail.ru"]
description = "An out-of-box wraper of the `trie_db` crate"
homepage = "https://github.com/rust-util-collections/vsdb"
repository = "https://github.com/rust-util-collections/vsdb"

[dependencies]
serde = { workspace = true }
trie-db-fun = { workspace = true }
reference-trie-fun = { workspace = true }

ruc = { workspace = true }
vsdb = { workspace = true }
vsdb_hash_db = { workspace = true }

[features]
default = ["rocks_backend"]

rocks_backend = ["vsdb/rocks_backend"]
parity_backend = ["vsdb/parity_backend"]

bcs_codec = ["vsdb/bcs_codec"]
json_codec = ["vsdb/json_codec"]
msgpack_codec = ["vsdb/msgpack_codec"]
